### ISSUE TITLE
Change leadership is bug

### ISSUE THREAD

**Issue by Ranoru24** [fieryhenry/Battle-Cats-Save-File-Editor#11]
I tried to use this cheat to change leadership (my current is 200) but after I change it, it turns to 0

**Comment by fieryhenry** [comment]
What are you changing your leadership to?

**Comment by Ranoru24** [comment]
> What are you changing your leadership to?

I changed it to 500

**Comment by fieryhenry** [comment]
Is this fixed in the latest release?
