### ISSUE TITLE
Unhandled exception: index was outside the bounds of the array

### ISSUE THREAD

**Issue by njuff22** [fieryhenry/Battle-Cats-Save-File-Editor#13]
-encountered upon trying to edit a save file;
![image](https://user-images.githubusercontent.com/22568144/116282603-42539a00-a78b-11eb-8a98-66da032168c0.png)
-tried adding 1901 cat tickets, upon which issue appears and program crashes

**Comment by fieryhenry** [comment]
Hmm ok, could you send me your save, you could attach it as a comment on this issue, or dm on discord?

**Comment by njuff22** [comment]
turned out to be an issue with NoxPlayer, not the save editor
