### ISSUE TITLE
GAMATOTO crashing game upon trying to open after having used "generate new game code"

### ISSUE THREAD

**Issue by njuff22** [fieryhenry/Battle-Cats-Save-File-Editor#14]
tested on both mobile and emulator, having transferred save between them
file:
https://mega.nz/file/ndVyFLiR#nHZO1458p69r132q3Vvf3HKy_ad2o3vdcHbUbC9LX2s

**Comment by fieryhenry** [comment]
If you use option 25 then 5, it should fix your gamatoto
