### ISSUE TITLE
[Request] Linux/Debian build

### ISSUE THREAD

**Issue by batectin** [fieryhenry/Battle-Cats-Save-File-Editor#21]
Hi there, could you make a build for Linux command line? I saw that you use C#/.NET in the source code but it's kinda hard to build it in Linux env. Thank you so much :)

**Comment by DanKGooGLy** [comment]
+1. Why did you close this issue?

**Comment by batectin** [comment]
> +1. Why did you close this issue?

Oh cuz I used wine in the end to run this. You also need wine-mono msi as an extra library dependency as well tho.
