### ISSUE TITLE
Catfruit and Catseeds

### ISSUE THREAD

**Issue by seifer69er** [fieryhenry/Battle-Cats-Save-File-Editor#23]
Using Menu option 21>2
Changing all catfruit/seeds to 256 will yield 256 of each item totalling 256x 15 = 3840
When loaded in game only 256 of Purple seed is shown and recorded. (first 256 in list)

Issue is; Catfruit Storage will only hold 256 MAX of all items.

Suggest capping mass edit from 256 to 17 . (256max/15types = 17of ea) 
OR
Suggest capping mass edit to only cat fruits
32 Catfruits ea, (256max/8types = 32 of ea catfruits and no cat seeds)

**Comment by fieryhenry** [comment]
Added in latest release
