### ISSUE TITLE
Talent levels

### ISSUE THREAD

**Issue by unbaseduser** [fieryhenry/Battle-Cats-Save-File-Editor#29]
When you choose to edit talents for a cat that has a **gain tough vs**, **gain massive damage** or **gain money up** talent, the editor allows you to enter a max level of 10, which should be 1 instead. See screenshots below for what happens if you choose a level that's not 1.
![Screenshot_20211211-205713_The_Battle_Cats](https://user-images.githubusercontent.com/95969852/145679536-f6d321b7-3842-4991-b221-0ba18dda0d50.png)
![Screenshot_20211211-205702_The_Battle_Cats](https://user-images.githubusercontent.com/95969852/145679539-28b136f3-6160-4bc8-b278-6823e2af4f38.png)
![Screenshot_20211211-205728_The_Battle_Cats](https://user-images.githubusercontent.com/95969852/145679540-bcf9df3d-5519-440d-bb73-2e5c02d77d3a.png)
e

**Comment by fieryhenry** [comment]
Should be fixed in latest release
