### ISSUE TITLE
[Feature request] Transfer save file to game (similar to the old BackupManagerEN)

### ISSUE THREAD

**Issue by MGJerry** [fieryhenry/Battle-Cats-Save-File-Editor#31]
Is it possible to integrate the "restore a backup" feature of Lethal's BackupManagerEN into the editor?
Although his program haven't been updated in a long time, it's still works (to an extent, and somewhat buggy)

This would really help ease the process of getting the edited save file running, and also remove the reliance on a rooted android device/emulator

**Comment by fieryhenry** [comment]
I thought that the restore feature no longer worked, but I just tested it now and it does actually work. I'll work on adding it in now.

**Comment by fieryhenry** [comment]
Actually, you seem to get the elsewhere error after transferring for a second time, not sure if i'll be able to bypass that as it's probably because i'm using the old restore save request instead of the official 10.4.0+ secure request, that idk how to produce.

**Comment by MGJerry** [comment]
I have never enter the "save file is being used elsewhere" myself, so I'm not exactly sure either (probably because I transfered the save back to the same device/emulator everytime)

But I'm pretty sure PONOS has some ways of detecting the old system, because for me, the save file's inquiry code usually get change in the process.
There's also some minor glitch like stats not being transfer (ex. Renamed lineup, Stage's highscore)
